### PR TITLE
style: apply latest clippy suggestions

### PR DESCRIPTION
**Pull request by jdrouet**
This has just been made by doing `cargo clippy --fix --tests`.

clippy 0.1.84 (e92993dbb4 2024-10-18)

### CODE REVIEW

**Comment by udoprog** [comment]
@RazrFalcon It seems like there's something in the repo settings on Github which seems to be preventing the [Github action](https://github.com/RazrFalcon/xmlparser/blob/master/.github/workflows/ci.yml) from running over this change. I don' seem tot have access to repo settings to review.

Could I get access to fix it or can transfer the repo to my user?

**Comment by udoprog** [comment]
I think I found the reason. There seems to be a new Github policy in place which disables workflow if a repo hasn't seen any activity for the last 60 days:
image.

**Comment by udoprog** [comment]
Thank you!

**Comment by jdrouet** [comment]
@udoprog and @RazrFalcon I think it would be worth creating an org for that project. I'd be happy to contribute more considering I have some libs depending on it 😉

**Comment by RazrFalcon** [comment]
We can just invite you to this project, if needed. No need for a project.
Also, you can always send a PR, so at least we could review your changes at first.

**Comment by udoprog** [comment]
Just to note I've already been given ownership of the package on crates.io so the code can be hosted anywhere as long as I can access the settings for the project. It would be nice to preserve the history (issues and discussions), so a project transfer is just the cleanest.

@jdrouet If there's anything you want to add or change I'd suggest opening up an issue so we can discuss it. My only focus right now is maintaining the project and ensuring that any bugs found are fixed and released to allow other people like me to safely continuing depending on it. An org might be an idea, but I'm not convinced it's worth the overhead right now unless there are plans for major future developments.

**Comment by jdrouet** [comment]
Fair enough, you're right

**Pull request merged**
